apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8501
      protocol: TCP
      name: http
  selector:
    app: frontend
